### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by bdawg1989** [proferabg/EdiZon-Overlay#10]
The new update for OS16 works great, however, I've experienced 4 crashes during a 4 hour span of opening and activating game cheats and then opening and deactivating game cheats.

Here is the logs report:

https://pastebin.com/KcYvb9VG
https://pastebin.com/NtQ7B0yZ

Here is the dump 
https://easyupload.io/670s48

**Comment by proferabg** [comment]
Please post your cheat file, game id, and version that you are using it on.

**Comment by bdawg1989** [comment]
Ok, Here is my file for Pokemon Scarlet Cheats.

https://easyupload.io/o3h184

**Comment by bdawg1989** [comment]
The menu would open, and then disappear.  On trying to re-open the menu it would just crash.

**Comment by proferabg** [comment]
I believe this was caused by your cheat file not being formatted correctly. This was most likely caused by the incorrect brackets used inside 'A4B74EBC314F616A.txt'. The master code is using curly brackets '{}' instead of using square brackets '[]'. I noticed there was also an update so please reply if changing these fixes it or if you update you cheats if it still happens. If there is no reply in 3 days, I will close this issue as being resolved.

**Comment by bdawg1989** [comment]
Thanks for your reply!  I am working on new cheats for v1.2 and am no longer using the master code with the curly brackets and it's been working fine!  Tysm!
