### ISSUE TITLE
doesn't work with latest Edizon-SE

### ISSUE THREAD

**Issue by Semsemboy** [proferabg/EdiZon-Overlay#5]
Title says it all. Edizon SE version: 3.8.35

**Comment by proferabg** [comment]
> Title says it all. Edizon SE version: 3.8.35

I'm not sure what you mean. I have been using that version and it has been working fine. It's not exactly dependent on Edizon SE as it really relies more on **dmntcht** from atmosphere. If you are able to provide more details on your experience or provide steps to recreate your issue, I will be more than happy to diagnose it. Otherwise, if I receive no reply in 3 days, I will close this issue.

**Comment by Semsemboy** [comment]
It seems that the issue comes from edizon-se rather than from edizon-overlay
